name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - name: install libharu
        run: |
          mkdir -p /tmp/libharu
          cd /tmp/libharu
          wget https://github.com/libharu/libharu/archive/refs/tags/v2.4.3.tar.gz -O v2.4.3.tar.gz
          tar -xvzf v2.4.3.tar.gz
          mkdir build
          cd build
          cmake ../libharu-2.4.3
          ls -l /usr/local/include
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - run: zig fmt --check src/*.zig